### PR TITLE
:lipstick: change shevron style on testimonial qna

### PR DESCRIPTION
**Pull request by zubairhasrat**
# Improve Testimonial Q&A Component: Enhance SVG Arrow Animation

The current implementation of the SVG arrow in the Testimonial Q&A component uses a 180-degree rotation to indicate the expansion of a question. While functional, this approach results in a misalignment of the SVG when a question is opened, detracting from the overall user experience. Replace the 180-degree rotation animation with a transition to a minus symbol ("-").

## Type of Change

Please delete options that are not relevant:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist

Please ensure your PR fulfills the following requirements:

- [x] I have read and followed the [Contributing Guidelines](https://github.com/cuicui-project/contributing).
- [x] My code follows the code style of this project.
- [x] My code respect as much as possible the W3C standards with corresponding ARIA roles and html semantics.

- [x] I have performed a self-review of my code.
- [x] I have commented my code (if necessary), particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.

## Screenshots (if applicable)

If your PR includes UI changes, please include screenshots or GIFs showing the new behavior.

## Additional Context

Please provide any additional context or information that might be useful for the reviewers, such as links to relevant discussions, references, or issues.

### CODE REVIEW

**Comment by damien-schneider** [comment]
Thanks for the contribution! I’ll review it as soon as possible.

We might create a variant for this behavior since it uses client-side JavaScript. The original component was designed to work without any JavaScript, which had its own advantages. However, your version definitely makes the UI cleaner so we will definitively create a variant for this. 😉

**Comment by damien-schneider** [comment]
Thanks again for the PR! I’ve reviewed it, and I think the idea is great, as I mentioned in the issue. However, one of the key advantages of this Q&A component is that it doesn’t require any JavaScript. The solution you propose could be an interesting variant, but it would introduce JavaScript where it’s not currently needed.

The position of the arrow can actually be adjusted with simple CSS by modifying the `top` property. Additionally, the arrow animation in your solution feels a bit random. The animation proposed in the issue should serve as the inspiration, as it offers a much smoother SVG transformation.

**Comment by zubairhasrat** [comment]
> Thanks again for the PR! I’ve reviewed it, and I think the idea is great, as I mentioned in the issue. However, one of the key advantages of this Q&A component is that it doesn’t require any JavaScript. The solution you propose could be an interesting variant, but it would introduce JavaScript where it’s not currently needed.
> 
> The position of the arrow can actually be adjusted with simple CSS by modifying the `top` property. Additionally, the arrow animation in your solution feels a bit random. The animation proposed in the issue should serve as the inspiration, as it offers a much smoother SVG transformation.

Thanks for feedback, I have updated the as per requirement plz have a look!

**Comment by damien-schneider** [comment]
The changes look great, but I still believe there's no need for JavaScript in this case (which includes the `useRef` from React). Additionally, the 180-degree rotation isn't necessary anymore, thanks to the smooth animation that transforms the minus into an arrow.

Since Cuicui aims to offer the easiest way to copy-paste, it would be better to keep the `toggleIcon` in the same file as the variant. This avoids having an unknown import at the top of the file.

I've made some adjustments, but I can't create a PR directly on your branch. However, here are the modifications for `variant1` as an example.

```typescript
"use client";

import { cn } from "#/src/utils/cn";

export default function GradientQnAVariant1() {
  return (
    <div className="">
      <div className="absolute left-1/2 -translate-x-1/2 top-1/2 -translate-y-1/2">
        <AdvancedGradiant className="opacity-50" />
      </div>
      <div className=" space-y-2">
        <Testimonial
          title="What is the best thing about this product?"
          content="The best thing about this product is that it is very easy to use and it is very user-friendly. It is also very affordable and it is very easy to set up."
        />
        <Testimonial
          title="What is the best thing about this product?"
          content="The best thing about this product is that it is very easy to use and it is very user-friendly. It is also very affordable and it is very easy to set up."
        />
        <Testimonial
          title="What is the best thing about this product?"
          content="The best thing about this product is that it is very easy to use and it is very user-friendly. It is also very affordable and it is very easy to set up."
        />
      </div>
    </div>
  );
}

const Testimonial = ({
  title,
  content,
}: {
  title: string;
  content: string;
}) => {
  return (
    <div className="bg-neutral-500/10 hover:bg-neutral-500/20 border border-neutral-400/20 transition-all rounded-3xl overflow-hidden relative backdrop-blur-2xl">
      <details className="peer group max-h-96 overflow-hidden transition-all w-full transform-gpu">
        <summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-4 pr-6 group-open:pt-8 group-open:pl-8 duration-300  transition-all transform-gpu">
          <h6 className="text-lg tracking-tight text-neutral-600 dark:text-neutral-300 font-medium">
            {title}
          </h6>
          <ToogleIcon />
        </summary>
      </details>

      <div className="peer-open:max-h-40 max-h-0 overflow-hidden transition-all duration-500 text-neutral-700 dark:text-neutral-200 font-medium transform-gpu">
        <p className="p-8 m-2 bg-neutral-500/10 rounded-2xl ">{content}</p>
      </div>
    </div>
  );
};

const AdvancedGradiant = ({
  className,
}: {
  className?: string;
}) => {
  return (
    <>
      <style>
        {`
          @keyframes size-bounce {
            50% scale(0.8)
            100% scale(1)
          }
          @keyframes spin {
            100% rotate(360deg)
          }
        `}
      </style>
      <div
        className={cn(
          "size-[400px] relative transition-all transform-gpu",
          className,
        )}
      >
        <div className="absolute top-0 left-0 grid place-items-center w-full h-full transform-gpu">
          <div
            className={cn(
              "w-full h-full blur-3xl opacity-80 rounded-full transform-gpu",
            )}
            style={{
              background:
                "conic-gradient(#FF0080, #EE00FF, #00A6FF, #4797FF, #0044FF, #FF8000, #FF00CC)",
              animation: "spin 15s linear infinite",
            }}
          />
        </div>
        <div
          className="absolute top-0 left-0 grid place-items-center w-full h-full transform-gpu"
          style={{
            animation: "size-bounce 20s linear infinite",
          }}
        >
          <div
            className={cn(
              "size-[300px] absolute blur-2xl rounded-full transform-gpu",
            )}
            style={{
              background: "conic-gradient(#FFF, #12B4E6, #DC4CFC)",
              animation: "spin 10s linear infinite",
            }}
          />
        </div>
        <div
          className="absolute top-0 left-0 grid place-items-center w-full h-full transform-gpu"
          style={{
            animation: "size-bounce 10s linear infinite",
          }}
        >
          <div
            className={cn(
              "size-[300px] absolute blur-2xl rounded-full opacity-80 transform-gpu  direction-reverse",
            )}
            style={{
              background: "conic-gradient(#A6EFFF, #12ADE6, #4C63FC)",
              animation: "spin-left 15s linear infinite",
            }}
          />
        </div>
      </div>
    </>
  );
};

const ToogleIcon = () => {
  return (
    <button
      type="button"
      className="relative size-5 text-neutral-600 dark:text-neutral-300"
    >
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="w-3 h-0.5 bg-current transition duration-500 translate-x-0.5 ease-in-out transform-gpu group-open:rotate-0 rotate-45" />
        <div className="w-3 h-0.5 bg-current transition -translate-x-0.5 duration-500 ease-in-out transform-gpu group-open:rotate-0 -rotate-45" />
      </div>
    </button>
  );
};

```

**Comment by zubairhasrat** [comment]
> The changes look great, but I still believe there's no need for JavaScript in this case (which includes the `useRef` from React). Additionally, the 180-degree rotation isn't necessary anymore, thanks to the smooth animation that transforms the minus into an arrow.
> 
> Since Cuicui aims to offer the easiest way to copy-paste, it would be better to keep the `toggleIcon` in the same file as the variant. This avoids having an unknown import at the top of the file.
> 
> I've made some adjustments, but I can't create a PR directly on your branch. However, here are the modifications for `variant1` as an example.
> 
> ```ts
> "use client";
> 
> import { cn } from "#/src/utils/cn";
> 
> export default function GradientQnAVariant1() {
>   return (
>     <div className="">
>       <div className="absolute left-1/2 -translate-x-1/2 top-1/2 -translate-y-1/2">
>         <AdvancedGradiant className="opacity-50" />
>       </div>
>       <div className=" space-y-2">
>         <Testimonial
>           title="What is the best thing about this product?"
>           content="The best thing about this product is that it is very easy to use and it is very user-friendly. It is also very affordable and it is very easy to set up."
>         />
>         <Testimonial
>           title="What is the best thing about this product?"
>           content="The best thing about this product is that it is very easy to use and it is very user-friendly. It is also very affordable and it is very easy to set up."
>         />
>         <Testimonial
>           title="What is the best thing about this product?"
>           content="The best thing about this product is that it is very easy to use and it is very user-friendly. It is also very affordable and it is very easy to set up."
>         />
>       </div>
>     </div>
>   );
> }
> 
> const Testimonial = ({
>   title,
>   content,
> }: {
>   title: string;
>   content: string;
> }) => {
>   return (
>     <div className="bg-neutral-500/10 hover:bg-neutral-500/20 border border-neutral-400/20 transition-all rounded-3xl overflow-hidden relative backdrop-blur-2xl">
>       <details className="peer group max-h-96 overflow-hidden transition-all w-full transform-gpu">
>         <summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-4 pr-6 group-open:pt-8 group-open:pl-8 duration-300  transition-all transform-gpu">
>           <h6 className="text-lg tracking-tight text-neutral-600 dark:text-neutral-300 font-medium">
>             {title}
>           </h6>
>           <ToogleIcon />
>         </summary>
>       </details>
> 
>       <div className="peer-open:max-h-40 max-h-0 overflow-hidden transition-all duration-500 text-neutral-700 dark:text-neutral-200 font-medium transform-gpu">
>         <p className="p-8 m-2 bg-neutral-500/10 rounded-2xl ">{content}</p>
>       </div>
>     </div>
>   );
> };
> 
> const AdvancedGradiant = ({
>   className,
> }: {
>   className?: string;
> }) => {
>   return (
>     <>
>       <style>
>         {`
>           @keyframes size-bounce {
>             50% scale(0.8)
>             100% scale(1)
>           }
>           @keyframes spin {
>             100% rotate(360deg)
>           }
>         `}
>       </style>
>       <div
>         className={cn(
>           "size-[400px] relative transition-all transform-gpu",
>           className,
>         )}
>       >
>         <div className="absolute top-0 left-0 grid place-items-center w-full h-full transform-gpu">
>           <div
>             className={cn(
>               "w-full h-full blur-3xl opacity-80 rounded-full transform-gpu",
>             )}
>             style={{
>               background:
>                 "conic-gradient(#FF0080, #EE00FF, #00A6FF, #4797FF, #0044FF, #FF8000, #FF00CC)",
>               animation: "spin 15s linear infinite",
>             }}
>           />
>         </div>
>         <div
>           className="absolute top-0 left-0 grid place-items-center w-full h-full transform-gpu"
>           style={{
>             animation: "size-bounce 20s linear infinite",
>           }}
>         >
>           <div
>             className={cn(
>               "size-[300px] absolute blur-2xl rounded-full transform-gpu",
>             )}
>             style={{
>               background: "conic-gradient(#FFF, #12B4E6, #DC4CFC)",
>               animation: "spin 10s linear infinite",
>             }}
>           />
>         </div>
>         <div
>           className="absolute top-0 left-0 grid place-items-center w-full h-full transform-gpu"
>           style={{
>             animation: "size-bounce 10s linear infinite",
>           }}
>         >
>           <div
>             className={cn(
>               "size-[300px] absolute blur-2xl rounded-full opacity-80 transform-gpu  direction-reverse",
>             )}
>             style={{
>               background: "conic-gradient(#A6EFFF, #12ADE6, #4C63FC)",
>               animation: "spin-left 15s linear infinite",
>             }}
>           />
>         </div>
>       </div>
>     </>
>   );
> };
> 
> const ToogleIcon = () => {
>   return (
>     <button
>       type="button"
>       className="relative size-5 text-neutral-600 dark:text-neutral-300"
>     >
>       <div className="absolute inset-0 flex items-center justify-center">
>         <div className="w-3 h-0.5 bg-current transition duration-500 translate-x-0.5 ease-in-out transform-gpu group-open:rotate-0 rotate-45" />
>         <div className="w-3 h-0.5 bg-current transition -translate-x-0.5 duration-500 ease-in-out transform-gpu group-open:rotate-0 -rotate-45" />
>       </div>
>     </button>
>   );
> };
> ```

Thanks for the suggestions, and changes incorporated.

**Pull request closed without merging**
