### PR TITLE
✨ add new spinner loader component

### PR DESCRIPTION
**Pull request by Ahmad-Zahid**
# Pull Request

## Description
This PR includes addition of spinner loader component and its variants.

- **Related Issue:** No related issue

## Type of Change

Please delete options that are not relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist

Please ensure your PR fulfills the following requirements:

- [x] I have read and followed the [Contributing Guidelines](https://github.com/cuicui-project/contributing).
- [x] My code follows the code style of this project.
- [x] My code respect as much as possible the W3C standards with corresponding ARIA roles and html semantics.

- [x] I have performed a self-review of my code.
- [x] I have commented my code (if necessary), particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.

## Screenshots (if applicable)

image

## Additional Context

Please provide any additional context or information that might be useful for the reviewers, such as links to relevant discussions, references, or issues.

### CODE REVIEW

**Comment by damien-schneider** [comment]
Thanks a lot for the contribution !! The spinners are very cool, and the way they are done is very smart ! I've prepared minor changes after we'll merge this PR to improve a bit the UI and sometimes simplify the code ;)


https://github.com/user-attachments/assets/9185916b-70e7-43a4-8fcf-2bb61d5be0ec

For the RadioGroupButton, I think there is a much usable way to achieve it. We can inspire ourselve from the Shadcn RadioGroup which use Radix with the advantage of the onValueChange or defaultValue & much more which is a very good practice. Because it is much simpler and can be adapted which is not always the case which your approch of passing an object of option.

By the way by seeing the code, I've updated the simpleCheckRadioBox which you can update as it has much better semantic compared to the old one.

The advantage of it is that it has much better props and it is much more usable by using it that way :

```typescript
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"

export function RadioGroupDemo() {
  return (
    <RadioGroup defaultValue="comfortable">
      <div className="flex items-center space-x-2">
        <RadioGroupItem value="default" id="r1" />
        <Label htmlFor="r1">Default</Label>
      </div>
      <div className="flex items-center space-x-2">
        <RadioGroupItem value="comfortable" id="r2" />
        <Label htmlFor="r2">Comfortable</Label>
      </div>
      <div className="flex items-center space-x-2">
        <RadioGroupItem value="compact" id="r3" />
        <Label htmlFor="r3">Compact</Label>
      </div>
    </RadioGroup>
  )
}
```
Here is the component from https://ui.shadcn.com/docs/components/radio-group#installation
```typescript
"use client"

import * as React from "react"
import * as RadioGroupPrimitive from "@radix-ui/react-radio-group"
import { Circle } from "lucide-react"

import { cn } from "@/lib/utils"

const RadioGroup = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root>
>(({ className, ...props }, ref) => {
  return (
    <RadioGroupPrimitive.Root
      className={cn("grid gap-2", className)}
      {...props}
      ref={ref}
    />
  )
})
RadioGroup.displayName = RadioGroupPrimitive.Root.displayName

const RadioGroupItem = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Item>
>(({ className, ...props }, ref) => {
  return (
    <RadioGroupPrimitive.Item
      ref={ref}
      className={cn(
        "aspect-square h-4 w-4 rounded-full border border-primary text-primary ring-offset-background focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
        className
      )}
      {...props}
    >
      <RadioGroupPrimitive.Indicator className="flex items-center justify-center">
        <Circle className="h-2.5 w-2.5 fill-current text-current" />
      </RadioGroupPrimitive.Indicator>
    </RadioGroupPrimitive.Item>
  )
})
RadioGroupItem.displayName = RadioGroupPrimitive.Item.displayName

export { RadioGroup, RadioGroupItem }
```

What do you think about this proposal ?

**Comment by damien-schneider** [comment]
Feel free to create two separate PRs instead of one. This way, we can immediately focus on adding the loaders, and the CheckboxGroup can be addressed in a subsequent PR. :)

**Comment by Ahmad-Zahid** [comment]
@damien-schneider the demo looks great 🎉 
For the radio button group, you're right, we can go with your proposal that definitely handles more cases.

Lastly, for the current PR I'm moving the radio button group code out of this one so we can focus on loaders.

**Comment by damien-schneider** [comment]
Perfect! Separating the PRs is a much better approach, as it allows us to review and accept each part incrementally.

**Review by damien-schneider — APPROVED** [review]

**Pull request merged**
